/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class christmas_logo_02 extends GenericLogo
{
  static template_type = "Symbol"; // Translateable
  static template_title = "Present 02"; // Translateable
  static template_id = "present_02"; // no spaces
  static template_image = "img/symbols/present_02.png"; // no spaces
  


  static data = '<?xml version="1.0" encoding="UTF-8"?><!-- 2022-11-29 11:52:48 Generated by QCAD 3.27.6 SVG Exporter --><svg width="248.3732mm" height="185.4567mm" viewBox="58.868 90.733 248.3732 185.4567" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">    <g transform="scale(1,-1)">        <!-- Line -->        <path d="M58.868,-145.2492 L307.2412,-145.2492 "/>        <!-- Line -->        <path d="M307.2412,-204.0855 L58.868,-204.0855 "/>        <!-- Line -->        <path d="M73.8188,-276.1897 L291.5673,-276.1897 "/>        <!-- Line -->        <path d="M291.5673,-276.1897 L291.5673,-204.089 "/>        <!-- Line -->        <path d="M186.4713,-204.089 L186.4713,-276.1897 "/>        <!-- Line -->        <path d="M173.9336,-276.1897 L173.9336,-204.089 "/>        <!-- Line -->        <path d="M73.8188,-204.089 L73.8188,-276.1897 "/>        <!-- Line -->        <path d="M58.868,-204.0855 L58.868,-145.2492 "/>        <!-- Line -->        <path d="M168.9911,-145.2492 L168.9911,-204.0855 "/>        <!-- Line -->        <path d="M191.5231,-204.0855 L191.5231,-145.2492 "/>        <!-- Line -->        <path d="M307.2412,-145.2492 L307.2412,-204.0855 "/>        <!-- Arc -->        <path d="M179.4714,-145.2492 A83.2727,83.2727 0 0,1 122.1667,-91.8353"/>        <!-- Arc -->        <path d="M122.1667,-91.8353 A16.5267,16.5267 0 0,1 102.2883,-116.1312"/>        <!-- Arc -->        <path d="M102.2883,-116.1312 A110.0689,110.0689 0 0,1 179.4714,-145.2492"/>        <!-- Arc -->        <path d="M179.4714,-145.2492 A164.4639,164.4639 0 0,1 248.0636,-129.3835"/>        <!-- Arc -->        <path d="M248.0636,-129.3835 A15.5773,15.5773 0 0,1 243.6461,-100.6702"/>        <!-- Arc -->        <path d="M243.6461,-100.6702 A54.0791,54.0791 0 0,1 179.4714,-145.2492"/>    </g></svg>';

}
 