/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class Christmas_logo_01 extends GenericLogo
{
  static template_type = "Symbol"; // Translateable
  static template_title = "Present 01"; // Translateable
  static template_id = "present_01"; // no spaces
  static template_image = "img/symbols/present_01.png"; // no spaces

  
  static data = '<?xml version="1.0" encoding="UTF-8"?><!-- 2022-11-28 15:24:38 Generated by QCAD 3.27.6 SVG Exporter --><svg width="157.8645mm" height="169.2636mm" viewBox="95.4687 100.682 157.8645 169.2636" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">    <g transform="scale(1,-1)">        <!-- Line -->        <path d="M95.4687,-129.3354 L253.3333,-129.3354 "/>        <!-- Line -->        <path d="M253.3333,-171.4535 L95.4687,-171.4535 "/>        <!-- Line -->        <path d="M105.0078,-269.9456 L242.0832,-269.9456 "/>        <!-- Line -->        <path d="M242.0832,-269.9456 L242.0832,-171.4535 "/>        <!-- Line -->        <path d="M188.976,-171.4535 L188.976,-269.9456 "/>        <!-- Line -->        <path d="M161.3253,-269.9456 L161.3253,-171.4535 "/>        <!-- Line -->        <path d="M105.0078,-171.4535 L105.0078,-269.9456 "/>        <!-- Line -->        <path d="M95.4687,-171.4535 L95.4687,-129.3354 "/>        <!-- Line -->        <path d="M152.4035,-129.3354 L152.4035,-171.4535 "/>        <!-- Line -->        <path d="M197.0158,-171.4535 L197.0158,-129.3354 "/>        <!-- Line -->        <path d="M253.3333,-129.3354 L253.3333,-171.4535 "/>        <!-- Arc -->        <path d="M173.4,-129.34 A33.9907,33.9907 0 0,1 144.9978,-103.2169"/>        <!-- Arc -->        <path d="M144.9978,-103.2169 A10.4167,10.4167 0 0,1 140.9545,-123.6175"/>        <!-- Arc -->        <path d="M140.9545,-123.6175 A221.9308,221.9308 0 0,1 173.4004,-129.3354"/>        <!-- Arc -->        <path d="M173.4004,-129.3354 A60.6251,60.6251 0 0,0 203.2067,-101.3502"/>        <!-- Arc -->        <path d="M203.2067,-101.3502 A11.0364,11.0364 0 0,0 211,-122"/>        <!-- Arc -->        <path d="M211,-122 A145.5097,145.5097 0 0,0 173.4004,-129.3354"/>    </g></svg>';

}
 