/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class christmas_logo_03 extends GenericLogo
{
  static template_type = "Symbol"; // Translateable
  static template_title = "Present 03"; // Translateable
  static template_id = "present_03"; // no spaces
  static template_image = "img/symbols/present_03.png"; // no spaces

  static data = '<?xml version="1.0" encoding="UTF-8"?><!-- 2022-11-28 14:10:17 Generated by QCAD 3.27.6 SVG Exporter --><svg width="108.0311mm" height="225.6316mm" viewBox="124.9292 72.5009 108.0311 225.6316" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">    <g transform="scale(1,-1)">        <!-- Arc -->        <path d="M178.9448,-97.1832 A37.7019,37.7019 0 0,1 153,-73"/>        <!-- Arc -->        <path d="M153,-73 A7.4825,7.4825 0 0,1 144,-84"/>        <!-- Arc -->        <path d="M144,-84 A49.8339,49.8339 0 0,1 178.9448,-97.1832"/>        <!-- Arc -->        <path d="M178.9448,-97.1832 A74.4613,74.4613 0 0,1 210,-90"/>        <!-- Arc -->        <path d="M210,-90 A7.0527,7.0527 0 0,1 208,-77"/>        <!-- Arc -->        <path d="M208,-77 A24.4844,24.4844 0 0,1 178.9448,-97.1832"/>        <!-- Line -->        <path d="M124.9292,-97.1832 L232.9603,-97.1832 "/>        <!-- Line -->        <path d="M232.9603,-185.7093 L188.789,-185.7093 "/>        <!-- Line -->        <path d="M169.1,-186 L125,-186 "/>        <!-- Line -->        <path d="M125,-200 L169.1,-200 "/>        <!-- Line -->        <path d="M188.789,-199.9086 L232.9603,-199.9086 "/>        <!-- Line -->        <path d="M232.9603,-298.1325 L124.9292,-298.1325 "/>        <!-- Line -->        <path d="M124.9292,-298.1325 L124.9292,-97.1832 "/>        <!-- Line -->        <path d="M169.097,-97.1832 L169.097,-298.1325 "/>        <!-- Line -->        <path d="M188.789,-298.1325 L188.789,-97.1832 "/>        <!-- Line -->        <path d="M232.9603,-97.1832 L232.9603,-298.1325 "/>    </g></svg>';

}
 