class FivePointedStarLogo extends GenericLogo
{
  static template_title = "Five pointed star"; // Translateable
  static template_id = "logo_five_star_dev"; // no spaces
  static template_image = "img/logos/icon_five_pointed_star_black.png"; // no spaces

  static data = '<?xml version="1.0" encoding="UTF-8"?><!-- 2022-06-21 09:57:38 Generated by QCAD 3.27.6 SVG Exporter --><svg width="67.7333mm" height="63.5mm" viewBox="0.1553 -64.1098 67.7333 63.5" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">    <g transform="scale(1,-1)">        <!-- Polyline -->        <path d="M34.022,64.1098 L42.4887,40.1209 L67.8887,40.1209 L48.1331,24.5987 L55.1887,0.6098 L34.022,14.7209 L12.8553,0.6098 L19.9109,24.5987 L0.1553,40.1209 L25.5553,40.1209 Z" style="stroke:#000000;stroke-width:0.25;"/>    </g></svg>';
}