/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class HalloweenLogo_01 extends GenericLogo
{
  static template_type = "Logo"; // Translateable
  static template_title = "Halloween 1"; // Translateable
  static template_id = "logo_halloween_01"; // no spaces
  static template_image = "img/logos/HalloweenLogo_black_01.png"; // no spaces

  constructor(id, name, layout_method)
  {
    super( id, name, layout_method);
    this.options.Width = {
      adjustable: true,
      name: "Width",
      _val: 10,
      get val() {
        return this._val;
      },
      set val( v ) {
        if(v < 10){
        this._val = 10;
        }else{
        this._val = v;
        }
      },
      type: "float"
    };
    this.options.AutoSplit = {
      configurable: false,
      name: "Auto split",
      val: true,
      type: "bool"
    };
  }
  static data = '<?xml version="1.0" encoding="UTF-8"?><!-- 2022-10-20 10:26:28 Generated by QCAD 3.27.6 SVG Exporter --><svg width="295.7177mm" height="270.6957mm" viewBox="19.8601 54.2683 295.7177 270.6957" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">    <g transform="scale(1,-1)">        <!-- Arc -->        <path d="M152,-95 A131.7556,131.7556 0 0,0 173,-57"/>        <!-- Arc -->        <path d="M198,-66 A118.678,118.678 0 0,0 187.0324,-97.1723"/>        <!-- Arc -->        <path d="M198,-66 A16.6067,16.6067 0 0,1 173,-57"/>        <!-- Arc -->        <path d="M172,-105 A50.0321,50.0321 0 0,1 104,-109"/>        <!-- Arc -->        <path d="M104,-109 A53.0685,53.0685 0 0,1 33,-138"/>        <!-- Arc -->        <path d="M33,-138 A164.9447,164.9447 0 0,1 58,-308"/>        <!-- Arc -->        <path d="M58,-308 A42.4055,42.4055 0 0,1 110,-314"/>        <!-- Arc -->        <path d="M110,-314 A53.6502,53.6502 0 0,1 170,-314"/>        <!-- Arc -->        <path d="M170,-314 A46.5254,46.5254 0 0,1 230,-314"/>        <!-- Arc -->        <path d="M230,-314 A43.8857,43.8857 0 0,1 296,-296"/>        <!-- Arc -->        <path d="M296,-296 A194.3088,194.3088 0 0,1 296,-126"/>        <!-- Arc -->        <path d="M296,-126 A44.0165,44.0165 0 0,1 232,-107"/>        <!-- Arc -->        <path d="M232,-107 A46.9544,46.9544 0 0,1 172,-105"/>        <!-- Circle -->        <circle cx="130" cy="-170" r="40"/>        <!-- Circle -->        <circle cx="140" cy="-170" r="16"/>        <!-- Circle -->        <circle cx="220" cy="-170" r="40"/>        <!-- Circle -->        <circle cx="205" cy="-160" r="16"/>        <!-- Line -->        <path d="M280,-210 L224,-230 "/>        <!-- Line -->        <path d="M185,-234 L142,-234 "/>        <!-- Line -->        <path d="M110,-230 L60,-210 "/>        <!-- Arc -->        <path d="M60,-210 A103.3225,103.3225 0 0,1 145,-288"/>        <!-- Arc -->        <path d="M182,-288 A125.3036,125.3036 0 0,1 280,-210"/>        <!-- Line -->        <path d="M224,-230 L220,-250 "/>        <!-- Line -->        <path d="M182,-288 L182,-270 "/>        <!-- Line -->        <path d="M185,-250 L185,-234 "/>        <!-- Line -->        <path d="M142,-234 L142,-250 "/>        <!-- Line -->        <path d="M145,-270 L145,-288 "/>        <!-- Line -->        <path d="M113,-250 L110,-230 "/>        <!-- Line -->        <path d="M142,-250 L113,-250 "/>        <!-- Line -->        <path d="M185,-250 L220,-250 "/>        <!-- Line -->        <path d="M182,-270 L145,-270 "/>    </g></svg>';

}
