
class PoppyLogo extends GenericLogo
{
  static template_title = "Poppy"; // Translateable
  static template_id = "logo_poppy"; // no spaces
  static template_image = "img/logos/poppy_logo_black.png"; // no spaces

  constructor( id, name, layout_method )
  {
    super( id, name, layout_method );
    var this_class = this;

    this.options.AutoSplit.val =true;
  }

  static data = '<?xml version="1.0" encoding="UTF-8"?><!-- 2022-10-24 15:09:36 Generated by QCAD 3.27.6 SVG Exporter --><svg width="173.5526mm" height="210.4672mm" viewBox="54.3348 0.5997 173.5526 210.4672" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">    <g transform="scale(1,-1)">        <!-- Line -->        <path d="M54.3348,-198.3352 L79.4597,-211.0669 "/>        <!-- Line -->        <path d="M84.5467,-204.4312 L64,-194 "/>        <!-- Line -->        <path d="M67.9027,-180.6328 L93.0275,-193.3681 "/>        <!-- Line -->        <path d="M98.1181,-186.7288 L77,-175 "/>        <!-- Line -->        <path d="M82.7229,-161.3006 L104.6974,-178.1457 "/>        <!-- Line -->        <path d="M98.1181,-186.7288 L79.2939,-165.7738 "/>        <!-- Line -->        <path d="M77,-175 L93.0275,-193.3681 "/>        <!-- Line -->        <path d="M84.5467,-204.4312 L65.726,-183.4762 "/>        <!-- Line -->        <path d="M64,-194 L79.4597,-211.0669 "/>        <!-- Circle -->        <circle cx="142.4718898463622" cy="-112.7240554245774" r="15.95593556242401"/>        <!-- Arc -->        <path d="M160,-81 A22.1489,22.1489 0 0,0 198,-88"/>        <!-- Arc -->        <path d="M198,-88 A61.5974,61.5974 0 0,0 199.6369,-132.5739"/>        <!-- Arc -->        <path d="M199.6369,-132.5739 A59.8498,59.8498 0 0,0 132.8914,-173.8489"/>        <!-- Arc -->        <path d="M132.8914,-173.8489 A21.9336,21.9336 0 0,0 116,-143"/>        <!-- Arc -->        <path d="M160,-81 A24.1059,24.1059 0 0,1 132,-49"/>        <!-- Arc -->        <path d="M132,-49 A70.152,70.152 0 0,1 78.5636,-115.0761"/>        <!-- Arc -->        <path d="M78.5636,-115.0761 A27.61,27.61 0 0,1 116,-143"/>        <!-- Line -->        <path d="M170.6668,-46.5808 L195.7917,-59.3125 "/>        <!-- Line -->        <path d="M200.8787,-52.6733 L180.6011,-42.3968 "/>        <!-- Line -->        <path d="M184.2347,-28.8784 L209.3595,-41.6101 "/>        <!-- Line -->        <path d="M214.4501,-34.9744 L194.1689,-24.698 "/>        <!-- Line -->        <path d="M199.0584,-9.5462 L221.0294,-26.3878 "/>        <!-- Line -->        <path d="M227.8874,-17.4413 L205.9129,-0.5997 "/>        <!-- Line -->        <path d="M195.6294,-14.0194 L214.4501,-34.9744 "/>        <!-- Line -->        <path d="M209.3595,-41.6101 L194.1689,-24.698 "/>        <!-- Line -->        <path d="M182.058,-31.7183 L200.8787,-52.6733 "/>        <!-- Line -->        <path d="M195.7917,-59.3125 L180.6011,-42.3968 "/>    </g></svg>';
}