/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class RecWellLogo extends GenericLogo
{
  static template_title = "RecWell"; // Translateable
  static template_id = "logo_rec_well_dev"; // no spaces
  static template_image = "img/logos/RecWell_CMYK_Black.png"; // no spaces

  static data = '<?xml version="1.0" encoding="UTF-8"?><!-- 2022-10-06 08:14:12 Generated by QCAD 3.27.6 SVG Exporter --><svg width="74.2808mm" height="53.6483mm" viewBox="48.5306 50.3721 74.2808 53.6483" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">    <g transform="scale(1,-1)">        <!-- Line -->        <path d="M48.5306,-64.2063 L76.4039,-104.0152"/>        <!-- Line -->        <path d="M81.6657,-96.4971 L59.0547,-64.2169"/>        <!-- Line -->        <path d="M61.4162,-56.1471 L67.0583,-64.205"/>        <!-- Line -->        <path d="M73.75,-73.8 L94.9372,-104.0204"/>        <!-- Line -->        <path d="M100.1982,-96.5063 L89.5227,-81.2602"/>        <!-- Line -->        <path d="M98.935,-83.2784 L104.1965,-90.7926"/>        <!-- Line -->        <path d="M98.935,-83.2784 L112.2883,-64.2063"/>        <!-- Line -->        <path d="M122.8114,-64.2063 L112.2883,-64.2063"/>        <!-- Line -->        <path d="M85.7569,-64.205 L67.0583,-64.205"/>        <!-- Line -->        <path d="M59.0547,-64.2169 L48.5306,-64.2063"/>        <!-- Line -->        <path d="M61.4162,-56.1471 L85.7569,-56.1471"/>        <!-- Arc -->        <path d="M85.7569,-56.1471 A12.8393,12.8393 0 0,0 89.5227,-81.2602"/>        <!-- Line -->        <path d="M73.75,-73.8 L85.76,-73.8"/>        <!-- Arc -->        <path d="M85.7569,-64.205 A4.798,4.798 0 1,0 85.76,-73.8"/>        <!-- Circle -->        <circle cx="103.4032212039569" cy="-56.14650240804208" r="5.774395689042095"/>        <!-- Line -->        <path d="M122.8114,-64.2063 L104.1965,-90.7926"/>        <!-- Line -->        <path d="M100.1982,-96.5063 L94.9372,-104.0204"/>        <!-- Line -->        <path d="M81.6657,-96.4971 L76.4039,-104.0152"/>    </g></svg>';
}
