

class RibbonLogo extends GenericLogo
{
  static template_title = "Ribbon"; // Translateable
  static template_id = "logo_cancer_ribbon"; // no spaces
  static template_image = "img/logos/ribbon_black.png"; // no spaces
  
  static data = '<?xml version="1.0" encoding="UTF-8"?><!-- 2022-10-03 14:02:41 Generated by QCAD 3.27.6 SVG Exporter --><svg width="230.9266mm" height="454.1511mm" viewBox="-35.4633 -266.1255 230.9266 454.1511" version="1.1" xmlns="http://www.w3.org/2000/svg" style="stroke-linecap:round;stroke-linejoin:round;fill:none">    <g transform="scale(1,-1)">        <!-- Polyline -->        <path d="M-35.4633,-112.8076 L-2.8098,-188.0256"/>        <!-- Polyline -->        <path d="M-2.8098,-188.0256 A4695.42,4695.42 0 0 0 117.0587,6.3954"/>        <!-- Polyline -->        <path d="M117.0587,6.3954 A367.707,367.707 0 0 1 173,166"/>        <!-- Arc -->        <path d="M173,166 A89.8997,89.8997 0 1,1 -6,170"/>        <!-- Polyline -->        <path d="M-6,170 A449.079,449.079 0 0 1 44.4835,-0.1397"/>        <!-- Polyline -->        <path d="M79.1129,-52.8938 A3385.82,3385.82 0 0 0 164.3304,-187.6288"/>        <!-- Polyline -->        <path d="M-35.4633,-112.8076 A1936.66,1936.66 0 0 1 83.734,62.1267"/>        <!-- Polyline -->        <path d="M83.734,62.1267 A390.463,390.463 0 0 1 134.1343,207.195"/>        <!-- Arc -->        <path d="M134.1343,207.195 A54.9381,54.9381 0 1,1 25,203"/>        <!-- Polyline -->        <path d="M25,203 A104.758,104.758 0 0 0 134.1343,207.195"/>        <!-- Polyline -->        <path d="M25,203 A315.987,315.987 0 0 1 81.4929,58.4263"/>        <!-- Polyline -->        <path d="M117.0587,6.3954 A3909.9,3909.9 0 0 1 195.4633,-107.4618"/>        <!-- Line -->        <path d="M195.4633,-107.4618 L164.3304,-187.6288 "/>    </g></svg>';

}
